"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](overlay)\
[](bg:rose fg:overlay)\
$directory\
[](fg:rose bg:love)\
$git_branch\
$git_status\
[](fg:love bg:gold)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:gold bg:iris)\
$docker_context\
[](fg:iris bg:pine)\
$time\
[ ](fg:pine)\
$line_break$character"""

palette = 'rose_pine'

[palettes.rose_pine]
orange = "#ebbcba"
red = "#f38ba8"
maroon = "#eba0ac"
rose = "#ebbcba"
gold = "#f6c177"
love = "#eb6f92"
foam = "#9ccfd8"
sky = "#89dceb"
sapphire = "#74c7ec"
pine = "#31748f"
iris = "#c4a7e7"
text = "#e0def4"
base = "#191724"
surface = "#1f1d2e"
overlay = "#26233a"

[os]
disabled = false
style = "bg:gold fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:gold fg:text"
style_root = "bg:gold fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:surface bg:rose"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = ""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:pine"
format = '[[ $symbol $branch ](fg:base bg:love)]($style)'

[git_status]
style = "bg:love"
format = '[[($all_status$ahead_behind )](fg:base bg:love)]($style)'

[nodejs]
symbol = ""
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:base bg:gold)]($style)'

[c]
symbol = " "
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:base bg:gold)]($style)'

[rust]
symbol = ""
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:base bg:gold)]($style)'

[golang]
symbol = ""
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:base bg:gold)]($style)'

[php]
symbol = ""
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:base bg:gold)]($style)'

[java]
symbol = " "
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:base bg:gold)]($style)'

[kotlin]
symbol = ""
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:base bg:gold)]($style)'

[haskell]
symbol = ""
style = "bg:gold"
format = '[[ $symbol( $version) ](fg:base bg:gold)]($style)'

[python]
symbol = ""
style = "bg:foam"
format = '[[ $symbol( $version) ](fg:base bg:gold)]($style)'

[docker_context]
symbol = ""
style = "bg:surface"
format = '[[ $symbol( $context) ](fg:base bg:iris)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:rose"
format = '[[  $time ](fg:text bg:pine)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:gold)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:iris)'
vimcmd_replace_symbol = '[](bold fg:iris)'
vimcmd_visual_symbol = '[](bold fg:iris)'