"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_blue)\
$username\
[](bg:color_lavender fg:color_blue)\
$directory\
[](fg:color_lavender bg:color_bg3)\
$git_branch\
$git_status\
[](fg:color_bg3 bg:color_orange)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_orange bg:color_yellow)\
$docker_context\
[](fg:color_yellow)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
color_fg0 = '#fbf1c7'
color_fg1 = '#1e1e2e'
color_bg1 = '#f9e2af'
color_bg3 = '#f38ba8'
color_orange = '#fab387'
color_teal = '#94e2d5'
color_green = '#a6e3a1'
color_blue = '#89b4fa'
color_yellow = '#f9e2af'
color_red = '#f38ba8'
color_lavender = '#b4befe'


[username]
show_always = true
style_user = "bg:color_blue fg:color_fg0"
style_root = "bg:color_blue fg:color_fg0"
format = '[   ]($style)'

[directory]
style = "fg:color_fg0 bg:color_lavender"
format = "[ $path ]($style)"
truncation_length = 1

[git_branch]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_bg3)]($style)'

[git_status]
style = "bg:color_bg3"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_bg3)]($style)'

[nodejs]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_orange)]($style)'

[c]
symbol = " "
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_orange)]($style)'

[rust]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_orange)]($style)'

[golang]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_orange)]($style)'

[php]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_orange)]($style)'

[java]
symbol = " "
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_orange)]($style)'

[kotlin]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_orange)]($style)'

[haskell]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_orange)]($style)'

[python]
symbol = ""
style = "bg:color_orange"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_orange)]($style)'

[docker_context]
symbol = ""
style = "bg:color_yellow"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_yellow)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_yellow)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_yellow)'
vimcmd_replace_one_symbol = '[](bold fg:color_teal)'
vimcmd_replace_symbol = '[](bold fg:color_teal)'
vimcmd_visual_symbol = '[](bold fg:color_lavender)'
