#!/usr/bin/env sh
 
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off

# global settings
yabai -m config                              \
    auto_balance                on           \
    window_placement            second_child \
    top_padding                 15           \
    left_padding                15           \
    right_padding               15           \
    bottom_padding              15           \
    window_gap                  15           \
    layout                      bsp          \
    mouse_modifier              alt          \
    mouse_action1               move         \
    mouse_action2               resize       \
    mouse_drop_action           swap         \

echo "yabai configuration loaded.."
